name: LaTeX Build

on:
  push:
    branches: [ improvements ]
  pull_request:
    branches: [ improvements ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          
      - name: Build PDF
        run: |
          mkdir -p pdf
          latexmk -pdf main.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: main.pdf
